name: ThirstBar
version: '${project.version}'
main: me.orineko.thirstbar.ThirstBar
api-version: 1.13
description: 'A realistic thirst system with custom items, stages, and actions.'
softdepend: [PlaceholderAPI, ProtocolLib, WorldGuard, ItemsAdder, MMOItems]
commands:
  ThirstBar:
    description: Main ThirstBar management command.
  TB:
    description: Shortcut for the ThirstBar command.
  Refresh:
    description: Refresh your thirst bar.
  RefreshAll:
    description: Refresh all online players' thirst bars.
